import json
import asyncio
from typing import List, cast
from src.agent_template import AgentTemplate
from agent_framework.orchestrations import MagenticBuilder, MagenticPlanReviewRequest

from agent_framework import (
    AgentResponseUpdate,
    Message,
    WorkflowEvent,
)
from agent_framework.orchestrations import MagenticProgressLedger

class MagenticOrchestrator:
    """
    Magentic workflow orchestrator for dynamic multi-agent collaboration.
    
    This orchestrator uses a manager agent to coordinate specialized agents,
    dynamically selecting which agent should act next based on task progress
    and agent capabilities. Supports complex, open-ended tasks requiring
    iterative refinement.

    Source: https://learn.microsoft.com/en-us/agent-framework/workflows/orchestrations/magentic?pivots=programming-language-python
    """
    
    def __init__(self, agents: List[AgentTemplate], manager_agent: AgentTemplate):
        """
        Initialize the Magentic orchestrator.
        
        Args:
            agents: List of specialized agents for the manager to coordinate
            manager_agent: The manager agent responsible for orchestrating the workflow
        """
        self.agents = agents
        self.manager_agent = manager_agent
    
    async def run(
        self, 
        initial_message: str, 
        max_rounds: int = 10, 
        max_stalls: int = 3, 
        max_resets: int = 2,
        intermediate_outputs: bool = True
    ) -> str:
        """
        Execute the Magentic workflow without plan review.
        
        The manager will coordinate agents autonomously based on the task.
        
        Args:
            initial_message: The task or question for the workflow
            max_rounds: Maximum number of orchestration rounds (default: 10)
            max_stalls: Maximum stall count before replanning (default: 3)
            max_resets: Maximum number of replans allowed (default: 2)
            
        Returns:
            The final synthesized output from the manager
        """
        participants = [agent.agent for agent in self.agents]
        workflow = MagenticBuilder(
            participants=participants,
            intermediate_outputs=intermediate_outputs,
            enable_plan_review=False,
            manager_agent=self.manager_agent.agent,
            max_round_count=max_rounds,
            max_stall_count=max_stalls,
            max_reset_count=max_resets,
        ).build()        
        
        # Keep track of the last executor to format output nicely in streaming mode
        last_message_id: str | None = None
        output_event: WorkflowEvent | None = None
        async for event in workflow.run(initial_message, stream=True):
            if event.type == "output" and isinstance(event.data, AgentResponseUpdate):
                message_id = event.data.message_id
                if message_id != last_message_id:
                    if last_message_id is not None:
                        print("\n")
                    print(f"- {event.executor_id}:", end=" ", flush=True)
                    last_message_id = message_id
                print(event.data, end="", flush=True)

            elif event.type == "magentic_orchestrator":
                print(f"\n[Magentic Orchestrator Event] Type: {event.data.event_type.name}")
                if isinstance(event.data.content, Message):
                    print(f"Please review the plan:\n{event.data.content.text}")
                elif isinstance(event.data.content, MagenticProgressLedger):
                    print(f"Please review progress ledger:\n{json.dumps(event.data.content.to_dict(), indent=2)}")
                else:
                    print(f"Unknown data type in MagenticOrchestratorEvent: {type(event.data.content)}")

                # Block to allow user to read the plan/progress before continuing
                # Note: this is for demonstration only and is not the recommended way to handle human interaction.
                # Please refer to `with_plan_review` for proper human interaction during planning phases.
                await asyncio.get_event_loop().run_in_executor(None, input, "Press Enter to continue...")

            elif event.type == "output":
                output_event = event

        # The output of the Magentic workflow is a list of ChatMessages with only one final message
        # generated by the orchestrator.
        output_messages = cast(list[Message], output_event.data)
        output = output_messages[-1].text

        return output
    
    def __repr__(self) -> str:
        """String representation of the orchestrator."""
        agent_names = ", ".join([agent.name for agent in self.agents])
        return f"MagenticOrchestrator(manager={self.manager_agent.name}, agents=[{agent_names}])"